### ISSUE TITLE
Second Y-Axis with different Scale

### ISSUE THREAD

**Issue by x0tester0x** [AJRepo/PHPlot#2]
How can I add a second Y-Axis with a different Scale?

**Comment by AJRepo** [comment]
See the example documentation file, phplotdocs/ex-outbreak.html 

Basically you are defining a second plot after doing the first one. 

Key part is 

# Plot 2
$plot->SetDrawPlotAreaBackground(False); // Cancel background
$plot->SetDrawYGrid(False); // Cancel grid, already drawn

$plot->SetDataValues($data2);
# Set Y title for plot #2 and position it on the right side:
$plot->SetYTitle($y_title2, 'plotright');
