### ISSUE TITLE
Support of php 8?

### ISSUE THREAD

**Issue by michaelkeusch** [AJRepo/PHPlot#4]
Hello,
support phplot release-6.2.0 PHP 8?
Up to which PHP version is release-6.2.0 downward compatible?
Currently I am using release-6.2.0 with PHP7.4.
Thank you very much for your efforts.
Greetings Michael

**Comment by cth18012017** [comment]
Hello,
I have the same question to.
Or, there are a good alternative?

**Comment by cth18012017** [comment]
Michael can you solve the issue for your project?

**Comment by AJRepo** [comment]
Yes,  PHPlot is compatible with PHP 8.1 If you run into any errors - let me know.

**Comment by cth18012017** [comment]
Hello and good evening,
Thanks for the information. Is there a new release for 8.1?
Is PHPlot maintained again and is there a new PHPlot release with PHP8.2?
What is the difference between PHPlot and PHPOffice->PHPSpreqdsheet->Chart as an alternative?

I have one more big request, we are switching everything to compose. Please provide PHPlot as lib for compose!

With kind regards
Christian

**Comment by AJRepo** [comment]
There is not a planned release just for PHP 8.1 as the existing code works well. 

I see there are some suggested changes by linters like "declaring visibility of constants"   which I will be looking at, but don't see that as impacting PHPlot much. 

I've not used  PHPOffice so can't answer your question there. 

Composer: will look at that.  If you have suggestions in that regard - happy to see them.

**Comment by cth18012017** [comment]
Hi, thanks for the feedback.
It would be nice if you run your project as a composer project. In our code, we will check our deployed libraries for updates every 2 weeks. Our release policy dictates that we have a special treatment for libraries that are very outdated, as there may be security issue in there. But I can't judge that at the moment. When I am healthy again I can scan the sources you downloaded for vulnerabilities. However, I assume that you also have such scanners as Sonarcube, Black Duck and Dependency Checker in use.

Links:
https://www.w3resource.com/php/composer/create-publish-and-use-your-first-composer-package.php
https://getcomposer.org/doc/02-libraries.md
Übersetzt mit DeepL https://www.deepl.com/app/?utm_source=android&utm_medium=app&utm_campaign=share-translation

**Comment by cth18012017** [comment]
Is that helpfull for you?

**Comment by AJRepo** [comment]
yes. I see that I'd have to move everything into a namespace for composer. 

I created a "group" project at https://github.com/PHPlot for that top level. It's my first owned group project so I'll be experimenting with creating the namespace there. Let me know if you'd like to be a member or have any specific suggestions regarding namespace setup.

**Comment by cth18012017** [comment]
Great. 
What ist your nett release? Wichtig version.
Which issues and todos are in the next Release?
I think that is a good step to change to composer.
In the next week i Post a new failure in our project with PHP8.1.
