### ISSUE TITLE
composer usage

### ISSUE THREAD

**Issue by cth18012017** [AJRepo/PHPlot#7]
Hello,

i test this with composer.

in a project i create the file "composer.json":

{
	"require" : {
		"phplot/phplot" : "*"
	}
}

Now in a cmd-console i use:

composer update

Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires phplot/phplot, it could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

please test it from your side and drive it to a master branch with a concret version number.

**Comment by AJRepo** [comment]
The issue was that it was not released via packagist yet. That should be resolved with the release of 8.0.0-rc1 in master. Thanks for creating this issue.
