### ISSUE TITLE
exact version constraints (8.0.0.0-rc1) should be avoided if the package follows semantic versioning

### ISSUE THREAD

**Issue by cth18012017** [AJRepo/PHPlot#8]
This is the failure: require.phplot/phplot : exact version constraints (8.0.0.0-rc1) should be avoided if the package follows semantic versioning.

Composer.json:

"require" : {
		"phplot/phplot" : "8.0.0.0-rc1"
	},

better if i can use:

"require" : {
		"phplot/phplot" : "^8.0"
	},

composer update
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires phplot/phplot ^8.0, found phplot/phplot[v8.0.0.0-rc1] but it does not match your minimum-stability.

**Comment by AJRepo** [comment]
I think the issue you are experiencing is that your composer setup has minimum-stability=stable. 

However, the last release was tagged as 8.0.0.0-rc1 which composer regards as RC1 stability. 

You can change the minimum stability flag for this library or I am about to tag  v8.0.0.0 which composer will regard as stable so that should also resolve this issue.

**Comment by cth18012017** [comment]
Please Tag it to v8.1.0.0 like php8.1--Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 04.01.23, 00:40 schrieb AJRepo ***@***.***>:

   
  I think the issue you are experiencing is that your composer setup has minimum-stability=stable. 
  However, the last release was tagged as 8.0.0.0-rc1 which composer regards as RC1 stability. 
  You can change the minimum stability flag for this library or I am about to tag v8.0.0.0 which composer will regard as stable so that should also resolve this issue.

**Comment by AJRepo** [comment]
Thank you for the suggestion. I will run it by some other folks to see if that makes sense or if it should be independently versioned.
